// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6glGq2en78IZLGBnLa88dkGVEaue6cYE',
    appId: '1:591712058459:web:f0ba4d9e341029b836d37e',
    messagingSenderId: '591712058459',
    projectId: 'e-commerce-machine-test',
    authDomain: 'e-commerce-machine-test.firebaseapp.com',
    storageBucket: 'e-commerce-machine-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEhQvoP5uBMYwrJaZqWhlpagttqwJh0A8',
    appId: '1:591712058459:android:2ecc4a4831cb217f36d37e',
    messagingSenderId: '591712058459',
    projectId: 'e-commerce-machine-test',
    storageBucket: 'e-commerce-machine-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItTl3fRzx9yt7449KaU2YuJNsIZFlV4s',
    appId: '1:591712058459:ios:afad436f80282d1636d37e',
    messagingSenderId: '591712058459',
    projectId: 'e-commerce-machine-test',
    storageBucket: 'e-commerce-machine-test.firebasestorage.app',
    iosBundleId: 'com.example.machineTestFirebase',
  );
}
